spring.application.name=mutual-fund-evaluation
server.port=8088


spring.mvc.servlet.path=/mf/v1
server.servlet.context-path=/

logging.level.org.springframework.security=DEBUG


logging.level.root=INFO
loggin.level.org.springframework.web: INFO
logging.level.org.springframework.boot.autoconfigure.web: DEBUG



spring.h2.console.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/camsmfdb
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

jwt.secret=
jwt.expiration-ms=3600000
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html