spring.application.name=mutual-fund-evaluation
server.port=8089


spring.mvc.servlet.path=/
server.servlet.context-path=/

logging.level.org.springframework.security=DEBUG


# Actuator management endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator


# H2 Database
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:mfdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

jwt.secret=
jwt.expiration-ms=3600000